---
title: "NFL Salary Distribution Study"
output: html_document
---

<style type="text/css">
body {
  font-size: 14pt;
  font-family: -apple-system, BlinkMacSystemFont, sans-serif;
}
table > tbody > tr > td {
  font-family: "InputMono-Regular", monospace;
  font-size: 12pt;
}
table > tbody > tr > td:first-of-type {
  font-family: inherit;
  font-size: inherit;
}
td:last-of-type {
  background-color: #eeeeee;
}
</style>


```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("kableExtra")
# devtools::install_github("topfunky/gghighcontrast")

library(kableExtra)
library(tidyverse)
library(gghighcontrast)

source("nfl-scrape-over-the-cap.R")
source("gini.R")
salaries = otc_load_and_cache_data_for_all_positions()

salary_percentiles <- salaries %>%
  group_by(Position) %>%
  # Calculate percentiles
  summarize(
    n = n(),
    gini = gini(SalaryInDollars),
    p50 = quantile(SalaryInDollars, probs = .50, na.rm = TRUE),
    p90 = quantile(SalaryInDollars, probs = .90, na.rm = TRUE),
    # p95 = quantile(SalaryInDollars, probs = .95, na.rm = TRUE),
    p99 = quantile(SalaryInDollars, probs = .99, na.rm = TRUE),
    stddev = sd(SalaryInDollars)
  )

position_abbreviations = data.frame(
  Position = c(
    "quarterback",
    "running-back",
    "fullback",
    "wide-receiver",
    "tight-end",
    "left-tackle",
    "left-guard",
    "center",
    "right-guard",
    "right-tackle",
    "interior-defensive-line",
    "edge-rusher",
    "linebacker",
    "safety",
    "cornerback",
    "kicker",
    "punter",
    "long-snapper"
  ),
  Position_abbr = c(
    "QB",
    "RB",
    "FB",
    "WR",
    "TE",
    "LT",
    "LG",
    "C",
    "RG",
    "RT",
    "IDL",
    "ER",
    "LB",
    "S",
    "CB",
    "K",
    "P",
    "LS"
  )
)

salaries <-
  salaries %>%
  left_join(salary_percentiles, by = c("Position")) %>%
  left_join(position_abbreviations, by = c("Position"))

```

## Percentiles

```{r percentiles, echo=FALSE}

salary_percentiles %>%
  arrange(-stddev) %>%
  # Format
  mutate(
    p50 = scales::dollar(p50),
    p90 = scales::dollar(p90),
    # p95 = scales::dollar(p95),
    p99 = scales::dollar(p99),
    stddev = scales::dollar(stddev)
  ) %>%
  knitr::kable(align="r", caption="NFL Salary Percentiles by Position") %>%
  kable_styling()

```

## Plot

Histogram

```{r plot-histogram, echo=FALSE, warning=FALSE, fig.asp=1.1}

ggplot(data = salaries,
       aes(x = SalaryInDollars)) +
  geom_histogram(fill = "#22d800", binwidth=1000000) +
  theme_high_contrast(
    foreground_color = "black",
    background_color = "white",
    base_family = "InputMono"
  ) +
  # Reference lines for percentiles
  # 50th percentile
  geom_vline(aes(xintercept = p50), color = "#999999") +
  # geom_text(
  #   aes(x = p50, y = 145, label = "50%"),
  #   angle = 90,
  #   hjust = 1,
  #   vjust = 1.5,
  #   color = "#999999",
  #   family = "InputMono"
  # ) +
  # 90th percentile
  geom_vline(aes(xintercept = p90), color = "#999999") +
  geom_text(
    aes(x = p90, y = 90, label = "90%"),
    angle = 90,
    hjust = 1,
    vjust = 1.5,
    color = "#999999",
    family = "InputMono",
    size=2.5
  ) +
  scale_x_continuous(labels = scales::label_number_si()) +
  scale_y_log10() +
  labs(title = "NFL Salary Distribution",
       subtitle = glue("Displaying {nrow(salaries)} player salaries by position. Reference lines at 50th\nand 90th percentiles."),
       y="number of players",
       x="salary",
       caption="Author: topfunky.com • Data: overthecap.com") +
  facet_wrap( ~ Position, ncol = 3)

```

Dot plot

```{r plot-dot, echo=FALSE, warning=FALSE}

salaries_with_color <-
  salaries %>% mutate(percentile_label = if_else(SalaryInDollars >= p90, "p90", "default"))

ggplot(data = salaries_with_color,
       aes(x = SalaryInDollars, y = Position_abbr, color = percentile_label)) +
  
  scale_color_manual(values = c("p90" = "#22d800", "default" = "#999999")) +
  geom_jitter() +
  
  theme_high_contrast(
    foreground_color = "black",
    background_color = "white",
    base_family = "InputMono"
  ) +
  theme(legend.position = "none") +
  
  scale_x_continuous(labels = scales::label_number_si()) +
  labs(
    title = "NFL Salary Distribution",
    subtitle = glue(
      "Displaying {nrow(salaries)} player salaries by position.\n90th percentile in green."
    ),
    y = "position",
    x = "salary",
    caption = "Author: topfunky.com • Data: overthecap.com"
  )

```
